export const data = {
    shotType: [
        'close-up', "Environmental portrait", "Rule of thirds composition", "Flat lay composition", "Abstract imagery",
        "HDR", "Macro shot", "extreme close-up", "Candid shot", "Establishing shot", "Upward facing shot", "Silhouette shot", 
        "Still life arrangement", "Medium shot", "Dutch angle", "Low-angle view", "Reaction shot", "Whip pan", "Cutaway view", 
        "Over-the-shoulder view", "Worm's-eye view", "High-angle view", "Wide shot", "Full shot", 'long shot'],

    shotStyle: [
        'polaroid', "Digital manipulation", "Bokeh blur", "Posterized effect", "Lomography", "Backlit", "Chiaroscuro lighting",
        "Pinhole image", "Soft focus", "Orton effect", "Selective focus", "Ghosting multi-exposure", "Reflected panorama",
        "Double exposure", "Underwater capture", "Cyanotype", "Ambrotype",  "Ultraviolet", "Mezzotint", "Sepia tone", "Tinted",
        'monochrome', 'tilt-shift', 'long exposure', 'color splash', "Solarized impression"],

    media:[
        'Photo of a', 'Picture of a', "Collage", "Mirror reflection of a", 'portrait of a', "Watercolor of a", 
        "Isometric representation of a", "Origami of a", "Impasto painting of a","Stained glass representation of a", 
        "Relief print of a", "Aquatint of a", "Batik design of a", "Encaustic painting of a", "Gouache painting of a", 
        "Ink drawing of a", "Linocut of a", "Charcoal sketch of a", "Oil painting of a", "Op art pattern of a", "Mosaic creation of a",
        "Papercut artwork of a", "8-bit representation of a", "Holographic display of a", "Sgraffito artwork of a", 
        "Sumi-e brushwork of a", "Chinese brush painting of a", "Drypoint of a", "Collagraph print of a", "Woodcut print of a", 
        "Terracotta figure of a", "Bronze sculpture of a",  "Pixel art of a", "Side profile of a", "Folk art of a", 
        "Modernist interpretation of a", "Bohemian style depiction of a", "Mixed media artwork of a", "Silk screen of a", 
        "Panorama of a", "Classical version of a", "Tapestry design of a", "Trompe-l'œil mural of a",
        "Retro style illustration of a", "Vintage photo of a", 'scupture of a', "Time-lapse of a", 'infographic of a', 
        '3D model of a', 'digital render of', 'graphic design of', 'mosaic of a', 'bird\'s eye veiw of', 'aerial view of', 
        'sketch of a', 'drawing of a', 'illustration of a', 'Painting of a', 'drone shot of a', '50n\'s tv show of a', 
        'comic book of a', 'poster of a', ],

    adjective:[    
        'colorful', 'shadowy', 'vintage', 'blurry', 'bright', 'dim', 'neon', 'shiny', 'faded', 'sharp', 'vibrant', 'splattered', 'warped', 'glowing', 'retro',
        'negative', 'cartoonish', 'silhouetted', 'layered', 'tinted', 'airy', 'opaque', 'holographic', 'neon', 'smooth', 
        'crinkled', 'sparkling', 'matte', 'glossy', 'distorted', 'symmetrical', 'asymmetrical', 'illuminated',
        'dotted', 'striped', 'embossed', 'noisy', 'smoky', 'clear', 'dusty', 'streaked',
        'glitchy', 'feathery', 'metallic', 'crystal-clear', 'dreamy', 'golden-hued',
        'silver-toned', 'velvet-textured', 'lustrous', 'muted', 'dull', 'electric', 'sandy', 'polished', 'mossy', 
        'granulated', 'frosty', 'fluorescent', 'sleek', 'jagged', 'pristine', 'clouded',
        'etched', 'serrated', 'dewy', 'burnished', 'lacy', 'sable', 'cobalt', 'rain-soaked', 'furry', 'velour',
        'lacquered', 'chiseled', 'gauzy', 'harlequin', 'mottled', 'iridescent', 'sun-bleached', 'wind-swept', 'brilliant',
        'cerulean', 'mercurial', 'sequined', 'papyrus-textured', 'beaded', 'perforated', 'speckled',
        'chiffon-like', 'gingham-patterned', 'salt-crusted', 'spangled', 'denim-textured',
        'plush', 'cumulus-like', 'ebony-toned', 'caramelized', 'marbled',
        'turquoise-tinted', 'ebony', 'ivory-toned', 'tulle-like', 'opaque',
        'zesty', 'azure', 'tangerine-hued', 'ruby-red', 'platinum-bright', 'kintsugi', 'rough', 'wet', 'dry', 'loose', 'tight',
        'hard', 'cold', 'warm', 'hot', 'flat', 'thick', 'thin', 'young', 'old',
        'tall', 'short', 'heavy', 'light', 'empty', 'full', 'busy', 'quiet', 'fast', 'slow',
        'broad', 'narrow', 'rich', 'poor', 'loud', 'soft-spoken', 'wild', 'tame', 'clean', 'dirty',
        'fragrant', 'stinky', 'sweet', 'bitter', 'spicy', 'salty', 'sour', 'curly', 'straight', 'wavy',
        'polka-dotted', 'checkered', 'plaid', 'swirly', 'zigzag', 'fluffy', 'sticky', 'slippery', 'chubby', 'skinny',
        'cozy', 'chilly', 'steamy', 'icy', 'toasty', 'furry', 'bald', 'shaggy', 'sleek', 'bubbly',
        'wrinkled', 'smooth', 'cracked', 'holey', 'patched',

        //positive
        'attractive', 'elegant', 'charming', 'graceful', 'stunning', 'beautiful',
        'dapper', 'debonair', 'suave', 'sophisticated', 'refined', 'muscular',
        'radiant', 'mesmerizing', 'alluring', 'magnetic', 'captivating',
        'fit', 'toned', 'slender', 'svelte', 'athletic', 'hot', 'sexy', 'slutty',
        'gallant', 'heroic', 'statuesque', 'chiseled', 'majestic', 
        'adorable', 'bewitching', 'classy', 'dazzling', 'enthralling',
        'fetching', 'gorgeous', 'handsome', 'impeccable', 'jovial',
        'luminous', 'noble', 'outstanding', 'picturesque', 'quaint',
        'ravishing', 'sensational', 'timeless', 'undeniable', 'vivacious',
        'winsome', 'youthful', 'zealous', 'vibrant', 'urbane', 'irresistible',
        'polished', 'lively', 'irresistible', 'harmonious', 'genial', 
        'fascinating', 'enchanting', 'delightful', 'cheerful', 'amiable',

        // Neutral
        'tall', 'short', 'slim', 'curvy', 'brawny', 'thick',
        'plump', 'petite', 'muscular', 'lanky', 'sturdy', 'sleezy',

        // Negative
        'haggard', 'scrawny', 'gaunt', 'sloppy', 'frumpy', 'unhealthy',
        'greasy', 'pudgy', 'wrinkled', 'flabby', 'disheveled', 'fat', 'greedy',
        'drab', 'dull', 'worn-out', 'sallow', 'pale', 'unattractive', 'horrible', 
        'grungy', 'shabby', 'rugged', 'scruffy', 'unkempt', 'disgusting', 'whorish'],

    emotionAdjective: [
        'joyful', 'melancholy', 'euphoric', 'haunting', 'serene','frustrated', 'elated', 'lonely', 'triumphant', 'desolate',
        'passionate', 'anxious', 'hopeful', 'foreboding', 'nostalgic','ecstatic', 'apprehensive', 'contemplative', 'jubilant', 'mournful',
        'bewildered', 'invigorated', 'yearning', 'sorrowful', 'radiant','tormented', 'blissful', 'restless', 'enchanted', 'horrified',
        'content', 'bitter', 'amused', 'defeated', 'zealous','relieved', 'pensive', 'indignant', 'exhilarated', 'woeful',
        'affectionate', 'apathetic', 'reminiscent', 'infatuated', 'petrified','dreamy', 'irate', 'optimistic', 'pessimistic', 'lighthearted',
        'heavy-hearted', 'rebellious', 'subdued', 'eager', 'disenchanted','lovestruck', 'wistful', 'enraged', 'humorous', 'skeptical',
        'thrilled', 'offended', 'grateful', 'devastated', 'relaxed','agitated', 'inspired', 'humbled', 'determined', 'lost',
        'empowered', 'hesitant', 'confident', 'brooding', 'playful','intrigued', 'courageous', 'timid', 'ambitious', 'regretful'],

    subject: [
        'man', 'woman', 'bird', 'dog', 'child', 'elder', 'cat', 'fish', 'lighthouse',
        'robot', 'astronaut', 'flower', 'castle', 'octopus','mushroom', 'skeleton', 'spider', 'unicorn',
        'mermaid','dancer', 'warrior', 'mountain', 'river', 'book', 'statue', 'cloud', 'snail', 'pyramid', 'giant','alien', 
        'ninja', 'tiger', 'bus', 'train', 'whale', 'butterfly', 'volcano', 'teapot', 'knight',
        'witch', 'zombie', 'vampire', 'windmill', 'goblin','goddess', 'angel', 'demon', 'minotaur', 'cactus',
        'balloon', 'spaceship', 'island', 'star', 'moon','planet', 'comet', 'dragon', 'chef', 'pirate',
        'pharaoh', 'elf', 'werewolf', 'gnome', 'penguin','chameleon', 'wizard', 'troll', 'satellite', 'jellyfish',
        'sphinx', 'centaur', 'fairy', 'mummy', 'yeti','cyclops', 'alien', 'guitar', 'drum', 'violin', 'entity', 'structure', 
        'form', 'figure', 'element','object', 'thing', 'item', 'artifact', 'instrument',
        'device', 'mechanism', 'apparatus', 'tool', 'machine', 'being', 'creature', 'lifeform', 'specimen', 'organism',
        'matter', 'substance', 'material', 'medium', 'compound','concept', 'notion', 'idea', 'phenomenon', 'principle',
        'system', 'process', 'method', 'technique', 'practice','scheme', 'strategy', 'plan', 'model', 'blueprint',
        'pattern', 'template', 'mold', 'prototype', 'archetype','symbol', 'sign', 'token', 'emblem', 'badge',
        'impression', 'expression', 'manifestation', 'display', 'exhibit','scene', 'setting', 'landscape', 'terrain', 'environment',
        'sphere', 'domain', 'realm', 'territory', 'province', 'representation', 'illustration', 'depiction', 'portrayal', 'image',
        'region', 'zone', 'area', 'space', 'field', 'emperor', 'queen', 'viking', 'pharaoh', 'knight',
        'gladiator', 'pirate', 'noble', 'musketeer', 'warlord','shogun', 'minstrel', 'sage', 'prophet', 'monk',
        'priest', 'shaman', 'chieftain', 'explorer', 'scribe','inventor', 'philosopher', 'scholar', 'astrologer', 'alchemist',
        'cavalier', 'crusader', 'barbarian', 'matador', 'spartan','roman senator', 'tribesman', 'nomad', 'gypsy', 'huntsman',
        'outlaw', 'duelist', 'bard', 'druid', 'high priestess','geisha', 'courtesan', 'mercenary', 'hermit', 'oracle',
        'blacksmith', 'falconer', 'scribe', 'pilgrim', 'marshal','admiral', 'conquistador', 'cossack', 'berserker', 'mummy',
        'templar', 'necromancer', 'sorcerer', 'archer', 'mystic','guerrilla', 'scout', 'healer', 'herald', 'chieftess',
        'seer', 'ranger', 'artificer', 'gunfighter', 'summoner',

        //disney
        'Simba from The Lion King', 'Ariel from The Little Mermaid', 'Belle from Beauty and the Beast', 'Aladdin from Aladdin', 'Mulan from Mulan',
        'Pocahontas from Pocahontas', 'Tarzan from Tarzan', 'Moana from Moana', 'Rapunzel from Tangled', 'Elsa from Frozen',
        'Anna from Frozen', 'Olaf from Frozen', 'Cinderella from Cinderella', 'Aurora from Sleeping Beauty', 'Tiana from The Princess and the Frog',
        'Woody from Toy Story', 'Buzz Lightyear from Toy Story', 'Nemo from Finding Nemo', 'Dory from Finding Dory', 'Sully from Monsters, Inc.',
        'Mike Wazowski from Monsters, Inc.', 'Wall-E from Wall-E', 'Eve from Wall-E', 'Merida from Brave', 'Remy from Ratatouille',
        'Joy from Inside Out', 'Sadness from Inside Out', 'Lightning McQueen from Cars', 'Mater from Cars', 'Miguel from Coco',
        'Hiro Hamada from Big Hero 6', 'Baymax from Big Hero 6', 'Ralph from Wreck-It Ralph', 'Vanellope from Wreck-It Ralph', 'Jack Skellington from The Nightmare Before Christmas',
        'Hercules from Hercules', 'Megara from Hercules', 'Peter Pan from Peter Pan', 'Tinker Bell from Peter Pan', 'Robin Hood from Robin Hood',
        'Bambi from Bambi', 'Dumbo from Dumbo', 'Lady from Lady and the Tramp', 'Tramp from Lady and the Tramp', 'Pongo from 101 Dalmatians',
        'Perdita from 101 Dalmatians', 'Mowgli from The Jungle Book', 'Baloo from The Jungle Book', 'Quasimodo from The Hunchback of Notre Dame', 'Esmeralda from The Hunchback of Notre Dame',
        'Judy Hopps from Zootopia', 'Nick Wilde from Zootopia', 'Maui from Moana', 'Cruella de Vil from 101 Dalmatians', 'Scar from The Lion King',
        'Ursula from The Little Mermaid', 'Maleficent from Sleeping Beauty', 'Jafar from Aladdin', 'Hades from Hercules', 'Captain Hook from Peter Pan',
        
        //other fictional characters
        'Homura Akemi from Puella Magi Madoka Magica', 'Madoka Kaname from Puella Magi Madoka Magica', 'Mami Tomoe from Puella Magi Madoka Magica',
        'Lelouch Lamperouge from Code Geass', 'C.C. from Code Geass', 'Kallen Stadtfeld from Code Geass',
        'Shinji Ikari from Neon Genesis Evangelion', 'Asuka Langley Soryu from Neon Genesis Evangelion', 'Rei Ayanami from Neon Genesis Evangelion',
        'Holo from Spice and Wolf', 'Kraft Lawrence from Spice and Wolf',
        'Peter Griffin from Family Guy', 'Lois Griffin from Family Guy', 'Meg Griffin from Family Guy',
        'Harley Quinn from Batman: The Animated Series', 'Poison Ivy from Batman: The Animated Series',
        "Bob Belcher from Bob's Burgers", "Linda Belcher from Bob's Burgers", "Tina Belcher from Bob's Burgers",
        'Stan Smith from American Dad', 'Francine Smith from American Dad', 'Haley Smith from American Dad',
        'Korra from The Legend of Korra', 'Asami Sato from The Legend of Korra', 'Lin Beifong from The Legend of Korra',
        'Ichigo Kurosaki from Bleach', 'Rukia Kuchiki from Bleach', 'Orihime Inoue from Bleach', 'Alucard from Hellsing', 
        'Integra Hellsing from Hellsing', 'Seras Victoria from Hellsing', 'Light Yagami from Death Note', 'Misa Amane from Death Note', 
        'L from Death Note', 'Eren Yeager from Attack on Titan', 'Mikasa Ackerman from Attack on Titan', 
        'Historia Reiss from Attack on Titan', 'Saitama from One Punch Man', 'Fubuki from One Punch Man', 'Genos from One Punch Man',
        'Kaneki from Tokyo Ghoul', 'Touka Kirishima from Tokyo Ghoul', 'Rize Kamishiro from Tokyo Ghoul',
        'Ryuko Matoi from Kill la Kill', 'Satsuki Kiryuin from Kill la Kill', 'Ira Gamagoori from Kill la Kill',
        'Isaac and Miria from Baccano!', 'Ennis from Baccano!',
        'Rintarou Okabe from Steins;Gate', 'Kurisu Makise from Steins;Gate', 'Mayuri Shiina from Steins;Gate',
        'Frank Underwood from House of Cards', 'Claire Underwood from House of Cards',
        'Walter White from Breaking Bad', 'Skyler White from Breaking Bad', 'Jesse Pinkman from Breaking Bad',
        'Rick Sanchez from Rick and Morty', 'Beth Smith from Rick and Morty', 'Summer Smith from Rick and Morty',
        'BoJack Horseman from BoJack Horseman', 'Princess Carolyn from BoJack Horseman', 'Diane Nguyen from BoJack Horseman',
        'Sterling Archer from Archer', 'Lana Kane from Archer', 'Cheryl Tunt from Archer', 'Daphne Blake from Scooby-Doo', 
        'Velma Dinkley from Scooby-Doo', 'Scooby-Doo from Scooby-Doo', "Shaggy Rogers from Scooby-Doo", 
        "Dee Dee from Dexter's Laboratory", "Dexter from Dexter's Laboratory", "Mandark from Dexter's Laboratory", 
        'Blossom from The Powerpuff Girls', 'Bubbles from The Powerpuff Girls', 'Buttercup from The Powerpuff Girls', 
        'Miss Bellum from The Powerpuff Girls', 'Penny from The Amazing World of Gumball', 
        'Anais Watterson from The Amazing World of Gumball', 'Gumball Watterson from The Amazing World of Gumball', 
        'Korra from The Legend of Korra', 'Asami Sato from The Legend of Korra', 'Mako from The Legend of Korra',
        'Sam Manson from Danny Phantom', 'Jazz Fenton from Danny Phantom', 'Danny Fenton from Danny Phantom',
        'Starfire from Teen Titans', 'Raven from Teen Titans', 'Robin from Teen Titans', 
        'Candace Flynn from Phineas and Ferb', 'Isabella Garcia-Shapiro from Phineas and Ferb', 'Phineas Flynn from Phineas and Ferb', 
        'Princess Bubblegum from Adventure Time', 'Marceline the Vampire Queen from Adventure Time', 'Finn the Human from Adventure Time',
        'Mabel Pines from Gravity Falls', 'Wendy Corduroy from Gravity Falls', 'Dipper Pines from Gravity Falls', 
        'Gaz Membrane from Invader Zim', 'Dib Membrane from Invader Zim',
        'Azula from Avatar: The Last Airbender', 'Katara from Avatar: The Last Airbender', 'Aang from Avatar: The Last Airbender', 
        'Helga Pataki from Hey Arnold!', 'Phoebe Heyerdahl from Hey Arnold!', 'Arnold from Hey Arnold!',
        'Eliza Thornberry from The Wild Thornberrys', 'Debbie Thornberry from The Wild Thornberrys', 
        'Nigel Thornberry from The Wild Thornberrys', 'Ahsoka Tano from Star Wars: The Clone Wars', 
        'Padmé Amidala from Star Wars: The Clone Wars', 'Obi-Wan Kenobi from Star Wars: The Clone Wars',
        'Lana Kane from Archer', 'Cheryl Tunt from Archer', 'Sterling Archer from Archer', 
        'Mordecai from Regular Show', 'Eileen from Regular Show', 'Margaret Smith from Regular Show', 
        'Lumpy Space Princess from Adventure Time', 'Ice King from Adventure Time', 'BMO from Adventure Time',
        'Princess Ilana from Sym-Bionic Titan', 'Lance from Sym-Bionic Titan',
        'Puss in Boots from The Adventures of Puss in Boots', 'Dulcinea from The Adventures of Puss in Boots',
        'Bee from Bee and PuppyCat', 'PuppyCat from Bee and PuppyCat',
        'BoJack Horseman from BoJack Horseman', 'Princess Carolyn from BoJack Horseman', 'Diane Nguyen from BoJack Horseman',
        'Wirt from Over the Garden Wall', 'Beatrice from Over the Garden Wall', 'Greg from Over the Garden Wall',
        'Apple from Apple & Onion', 'Onion from Apple & Onion',
        'Steven Universe from Steven Universe', 'Garnet from Steven Universe', 'Pearl from Steven Universe', 
        'Amethyst from Steven Universe', 
        'Rick Sanchez from Rick and Morty', 'Beth Smith from Rick and Morty', 'Summer Smith from Rick and Morty',
        'Clarence from Clarence', 'Jeff Randell from Clarence', 'Mary Wendle from Clarence',
        'Star Butterfly from Star vs. the Forces of Evil', 'Marco Diaz from Star vs. the Forces of Evil', 
        'Jackie Lynn Thomas from Star vs. the Forces of Evil',
        'Kim Possible from Kim Possible', 'Shego from Kim Possible', 'Ron Stoppable from Kim Possible',
        'Sam from Totally Spies!', 'Clover from Totally Spies!', 'Alex from Totally Spies!',
        'Toph Beifong from Avatar: The Last Airbender', 'Suki from Avatar: The Last Airbender', 'Zuko from Avatar: The Last Airbender', 
        'Numbuh 3 from Codename: Kids Next Door', 'Numbuh 5 from Codename: Kids Next Door', 'Numbuh 1 from Codename: Kids Next Door',
        'Lila from Hey Arnold!', 'Rhonda Wellington Lloyd from Hey Arnold!', 'Gerald Johanssen from Hey Arnold!',
        'Terra from Teen Titans', 'Blackfire from Teen Titans', 'Beast Boy from Teen Titans', 
        'Jenny Wakeman from My Life as a Teenage Robot', 'Vexus from My Life as a Teenage Robot', 
        'Brad Carbunkle from My Life as a Teenage Robot',
        'Lila Rossi from Miraculous Ladybug', 'Alya Césaire from Miraculous Ladybug', 'Adrien Agreste from Miraculous Ladybug',
        'Tak from Tak and the Power of Juju', 'Jeera from Tak and the Power of Juju', 
        'Penny Proud from The Proud Family', 'Dijonay Jones from The Proud Family', 'Sticky Webb from The Proud Family', 
        'June from The Life and Times of Juniper Lee', 'Jody Irwin from The Life and Times of Juniper Lee', 
        'Ray Ray Lee from The Life and Times of Juniper Lee',
        'Yumi Yoshimura from Hi Hi Puffy AmiYumi', 'Ami Onuki from Hi Hi Puffy AmiYumi',
        'Trixie Tang from The Fairly OddParents', 'Vicky from The Fairly OddParents', 'Timmy Turner from The Fairly OddParents',
        
        //music
        'Joanna Noëlle Levesque', 'Lily Allen', 'Sky Ferreira', 'Ellie Goulding', 'Tove Lo', 'Lykke Li','Lights', 'Rina Sawayama','MØ', 'BANKS',
        'Chvrches (Lauren Mayberry)', 'Ryn Weaver','Daya', 'Jessie Ware','Little Boots', 'Marina Kaye','Tove Styrke', 'Birdy',
        'Aurora', 'Kim Petras','Zara Larsson', 'AlunaGeorge (Aluna Francis)','Bebe Rexha', 'Allie X',
        'Amy Macdonald', 'Grimes','Nina Nesbitt', 'Låpsley','Ella Eyre', 'Becky G','Taylor Swift', 'Ariana Grande', 
        'Selena Gomez', 'Demi Lovato', 'Camila Cabello', 'Halsey','Billie Eilish', 'Lorde','Katy Perry', 'Lana Del Rey',
        'Carly Rae Jepsen', 'Charli XCX','Hayley Williams', 'Zooey Deschanel','Tinashe', 'Alessia Cara',
        'Jhene Aiko', 'SZA','Kacey Musgraves', 'Maggie Rogers','Sigrid', 'Dua Lipa', 'Marina Diamandis', 'Florence Welch',
        'Melanie Martinez', 'Doja Cat', 'Clairo', 'Sabrina Carpenter', 'Madison Beer', 'Olivia Rodrigo', 'Ed Sheeran', 'Justin Timberlake', 
        'Bruno Mars', 'Drake', 'Post Malone', 'The Weeknd','Sam Smith', 'Kanye West',
        'Justin Bieber', 'John Mayer','Jason Derulo', 'Shawn Mendes','Adam Levine (Maroon 5)', 'Chris Brown','Usher', 'Harry Styles',
        'Zayn Malik', 'Calvin Harris','John Legend', 'Eminem','Kendrick Lamar', 'Childish Gambino (Donald Glover)',
        'Pharrell Williams', 'Pitbull','Troye Sivan', 'Nick Jonas','Macklemore', 'Charlie Puth','J. Cole', 'Liam Payne',

        //actors / actresses
        'Tatiana Maslany', 'Elisabeth Moss', 'Jodie Comer', 'Phoebe Waller-Bridge', 
        'Carrie Coon', 'Regina King', 'Kiernan Shipka', 'Christina Hendricks','Ruth Negga', 'Gemma Chan',
        'Aubrey Plaza', 'Janet Varney',  'Krysten Ritter', 'Melissa Benoist',  'Aja Naomi King', 'Gugu Mbatha-Raw',
        'Mackenzie Davis', 'Janelle Monáe',  'Ellie Kemper', 'Issa Rae',  'Gina Rodriguez', 'Constance Wu',
        'Karlie Kloss', 'Joan Smalls',  'Lily Aldridge', 'Jourdan Dunn',  'Gisele Bündchen', 'Candice Swanepoel',
        'Miranda Kerr', 'Liu Wen', 'Doutzen Kroes', 'Adriana Lima',    'Robert Downey Jr.', 'Scarlett Johansson', 
        'Chris Hemsworth', 'Natalie Portman', 'Leonardo DiCaprio', 'Kate Winslet',  'Brad Pitt', 'Angelina Jolie',
        'Tom Hanks', 'Meryl Streep', 'Will Smith', 'Jada Pinkett Smith', 'Chris Pratt', 'Zoe Saldana',
        'Benedict Cumberbatch', 'Tilda Swinton', 'Ryan Reynolds', 'Morena Baccarin','Dwayne Johnson', 'Michelle Rodriguez',
        'Christian Bale', 'Anne Hathaway','Daniel Craig', 'Naomie Harris','Henry Cavill', 'Amy Adams',
        'Ben Affleck', 'Gal Gadot','Chris Evans', 'Elizabeth Olsen', 'Emilia Clarke', 'Maisie Williams',
        'Chadwick Boseman', "Lupita Nyong'o",    'Jennifer Aniston', 'Courteney Cox', 'Lisa Kudrow','Kit Harington', 
        'Steve Carell', 'Rainn Wilson', 'Jenna Fischer', 'Mindy Kaling','Bryan Cranston', 'Aaron Paul', 'Betsy Brandt',
        'Ellen Pompeo', 'Sandra Oh', 'Chandra Wilson', 'Katherine Heigl',
        'Charlie Sheen', 'Jon Cryer', 'Conchata Ferrell','Hugh Laurie', 'Lisa Edelstein', 'Jennifer Morrison',
        'Matthew Fox', 'Evangeline Lilly', 'Yunjin Kim','Kaley Cuoco', 'Jim Parsons', 'Mayim Bialik',
        'Viola Davis', 'Karla Souza','Sarah Michelle Gellar', 'Alyson Hannigan','Johnny Depp', 'Keira Knightley'],

    clothing: {
        head:[
            // 0 - 1000 AD    
            'wearing a pileus', 'wearing a petasos', 'wearing a leather cap', 'wearing a hooded cloak',
            'wearing a phrygian cap', 'wearing a calautica','wearing a birrus', 'wearing a mitra',
            'wearing a diadem', 'wearing a tiara','wearing a kausia', 'wearing a pilleus',
            'wearing a felt cap', 'wearing a conical hat', 'wearing a stephane crown',

            // 1200s to 1500s
            'wearing a hennin', 'wearing a coif', 'wearing a liripipe', 'wearing a bycocket', 'wearing a chaperon', 
            'wearing a sugarloaf helmet', 'wearing a barbute', 'wearing a sallet', 'wearing a bascinet', 'wearing a wimple', 
            'wearing a turban',

            // 1500s to 1700s
            'wearing a tricorn', 'wearing a bicorne', 'wearing a cavalier hat', 'wearing a capotain', 'wearing a morion', 
            'wearing a bonnet', 'wearing a mob cap', 'wearing a conical hat', 'wearing a beret', "wearing a tam o' shanter",
            'wearing a kufi',

            // 1800s to 1900s
            'wearing a top hat', 'wearing a bowler hat', 'wearing a deerstalker', 'wearing a pillbox hat', 'wearing a cloche hat', 
            'wearing a boater', 'wearing a homburg', 'wearing a fedora', 'wearing a ushanka', 'wearing a panama hat', 
            'wearing a pith helmet', 'wearing a kepi', 'wearing a fez', 'wearing a zucchetto', 'wearing a sombrero',

            // 2000s to current day
            'wearing a beanie', 'wearing a snapback', 'wearing a baseball cap', 'wearing a trucker hat', 'wearing a sun hat', 
            'wearing a bucket hat', 'wearing a bandana', 'wearing a headscarf', 'wearing a ski mask', 'wearing a balaclava',
            'wearing a headwrap', 'wearing a fascinator', 'wearing a hijab', 'wearing a niqab', 'wearing a chullo', 
            'wearing a toque', 'wearing a snood', 'wearing a do-rag', 'wearing a durag', 'wearing a visor', 
            'wearing a flat cap', 'wearing a newsboy cap', 'wearing a beret',

            //fantasy
            'wearing a moonbeam silk scarf',
            'wearing a solar flare headdress',
            'wearing a feather hat', 'wearing a witch-hat','wearing a charmed choker',
            'wearing a shawl','wearing a robe',"wearing a wizard's hat",'wearing a mystic mask',
            'wearing a bandana', 'with medusa snake hair',
            'wearing a scarf',
        ],
    
        body:[
            // 0 - 1000 AD    
            'wearing a sakkos', 'wearing a tunic', 'wearing a toga','wearing a stola', 'wearing a clavi',
            'wearing a pallium', 'wearing a dalmatica','wearing a chlamys', 'wearing a peplos',
            'wearing a himation', 'wearing a chiton','wearing a fibula', 'wearing a paenula',
            'wearing a subligar', 'wearing a tunica','wearing a spartan cloak', 'wearing a palla',
            'wearing a lorica', 'wearing a surcoat','wearing an exomis', 'wearing a strophium',

            // 1200s to 1500s
            'wearing a doublet', 'wearing a surcoat', 'wearing a gambeson', 'wearing a bodice', 'wearing a tabard',
            
            // 1500s to 1800s
            'wearing a waistcoat', 'wearing a jerkin', 'wearing a corset', 'wearing a chemise', 'wearing a justacorps', 
            'wearing a spencer jacket', 'wearing a stays', 'wearing a caraco', 'wearing a frock coat', 'wearing a pelisse',
            
            // 1900s
            'wearing a vest', 'wearing a cardigan', 'wearing a blazer', 'wearing a polo shirt', 'wearing a turtleneck',
            'wearing a windbreaker', 'wearing a bomber jacket', 'wearing a tank top', 'wearing a crop top', 'wearing a camisole',
            'wearing a poncho', 'wearing a halter top', 'wearing a sweater', 'wearing a bolero', 'wearing a pullover',

            // 2000s to current day
            'wearing a hoodie', 'wearing a graphic tee', 'wearing a wrap top', 'wearing a tube top', 'wearing a mesh top', 
            'wearing a cold shoulder top', 'wearing a peplum top', 'wearing a henley shirt', 'wearing a bandeau', 'wearing a shrug',
            'wearing a kebaya', 'wearing a kimono', 'wearing a kurta', 'wearing a qipao', 'wearing a dashiki', 
            'wearing a kaftan', 'wearing a kurti', 'wearing a batik shirt', 'wearing a barong Tagalog', 
            'wearing a jellabiya', 'wearing a poncho', 'wearing a guayabera', 'wearing a bolero', 
            'wearing a choli', 'wearing a rash guard', 'wearing a tankini', 'wearing an off-shoulder blouse', 
            'wearing a tunic', 'wearing a sari blouse', 'wearing a salwar kameez',
                
            // fantasy
            'wearing an enchanted cape','wearing a lace gown','wearing a corset','wearing a woven tunic',
            'wearing a celestial bodice','wearing fae chainmail','wearing a scale dress','wearing a cloak of invisibility',
            'wearing an enchanted tunic','wearing a mantle','wearing a tunic','wearing a regal robe',
            'wearing a mystical mantle','wearing a warden cloak', 'wearing a shawl','wearing an armored corset',
            "wearing a spellcaster's shawl","wearing a warrior's breastplate",'wearing a celestial cape','wearing a dragonhide vest',
            "wearing an alchemist's apron","wearing a sorceress's skirt",'wearing a vestment',"wearing a sorcerer's sash"
        ],

        arms: [
            // fantasy
            'wearing bracers', 'wearing vambraces', 'wearing arm guards', 'wearing gauntlets', 'wearing armlets', 
            'wearing wristwraps', 'wearing wristbands', 'wearing pauldrons', 'wearing greaves', 'wearing handguards', 
            'wearing finger claws', 'wearing knuckle dusters', 'wearing wrist chains', 'wearing sleeve guards', 
            'wearing arm plates', 'wearing wrist shields', 'wearing forearm covers', 'wearing gloved chains', 
            'wearing hand plates', 'wearing knuckle guards',
        
            // all other
            'wearing sleeves', 'wearing long gloves', 'wearing short gloves', 'wearing mittens', 'wearing arm warmers', 
            'wearing sweatbands', 'wearing wristbands', 'wearing bracelets', 'wearing bangles', 'wearing cuffs', 
            'wearing shawls', 'wearing an arm cape', 'wearing armbands', 'wearing armlets', 'wearing gauntlets', 
            'wearing wristwraps', 'wearing bracers', 'wearing vambraces', 'wearing pauldrons', 'wearing arm guards', 
            'wearing sleeve garters', 'wearing lace gloves', 'wearing silk gloves', 'wearing fingerless gloves', 
            'wearing elbow gloves', 'wearing opera gloves', 'wearing sleeve protectors', 'wearing forearm guards', 
            'wearing chainmail sleeves', 'wearing leather arm straps', 'wearing detachable sleeves', 'wearing upper arm bands', 
            'wearing elbow pads', 'wearing sleeve cuffs', 'wearing buttoned cuffs', 'wearing cuffed sleeves', 
            'wearing fringed sleeves', 'wearing sleeve ruffles', 'wearing puffed sleeves',
        ],
        
        legs: [
             // old time (before 1300 AD)
            'wearing a tunic', 'wearing braies', 'wearing a loincloth', 'wearing leggings', 'wearing a chiton', 
            'wearing culottes', 'wearing a dhoti', 'wearing a kilt', 'wearing a sarong', 'wearing a toga', 
            'wearing a stola', 'wearing a tunica',

                // 1500s to 1800s
            'wearing breeches', 'wearing knickerbockers', 'wearing hose', 'wearing petticoats', 'wearing pantaloons',
            
            // 1900s
            'wearing bell-bottoms', 'wearing jodhpurs', 'wearing flared trousers', 'wearing culottes', 'wearing capri pants',
            'wearing pedal pushers', 'wearing drainpipe trousers', 'wearing bootcut jeans', 'wearing cargo pants', 'wearing khakis',
            
            // 2000s to current day
            'wearing skinny jeans', 'wearing joggers', 'wearing yoga pants', 'wearing leggings', 'wearing chinos', 
            'wearing boyfriend jeans', 'wearing harem pants', 'wearing jeggings', 'wearing sweatpants', 'wearing palazzo pants',
            'wearing track pants', 'wearing slacks', 'wearing corduroy trousers',
        
            // fantasy
            'wearing a chainmail skirt', 'wearing fae-forged leggings', 'wearing greaves', 'wearing trousers', 
            'wearing mystic pants', 'wearing a spellshield skirt',
            'wearing shielded leggings', 'wearing potion-pocketed pants',    
        ],
        outfits: [
            //fantasy
            "wearing an elven queen's regalia", "wearing a dragon rider's attire", "wearing a dwarven king's ensemble",
            "wearing grand wizard robes", "wearing a necromancer's dark garb", "wearing a fairy's shimmering dress",
            "wearing a beastmaster's rugged outfit", "wearing a mermaid's sequined attire", "wearing intricate steampunk gear",
            "wearing a vampire lord's cloak", "wearing a celestial mage's robe", "wearing a werewolf alpha's gear",
            "wearing a sand sorcerer's flowing attire", "wearing a time traveler's sophisticated outfit", 
            "wearing a space pirate's rugged jumpsuit","wearing a galactic empress's regalia", 
            "wearing a water nymph's silken ensemble", "wearing a shadow assassin's stealth gear",
            "wearing a spell-thief's enchanted attire", "wearing a glacial queen's gown", 
            "wearing a phoenix warrior's flaming outfit","wearing a demon slayer's fortified armor", 
            "wearing a sun priest's golden robes", "wearing a moon sorceress's mystical dress",
            "wearing a cosmic wanderer's starlit cloak", "wearing a void warrior's abyssal armor", 
            "wearing a sylph's wind-woven attire","wearing an ancient guardian's battle garb", 
            "wearing an arena champion's glorious ensemble", "wearing a puppeteer's intricate outfit",
            "wearing a seafarer's stormy attire", "wearing a ghost's ethereal garb", 
            "wearing a forest guardian's nature-infused ensemble","wearing a celestial blacksmith's star-forged armor",
            "wearing a time weaver's dimensional robes","wearing a sun dancer's radiant ensemble",
            "wearing a stormcaller's tempestuous attire","wearing a crystal sage's luminescent gown",
            "wearing a void knight's abyss-touched armor","wearing a ethereal bard's harmonic tunic",
            "wearing a fire nomad's blazing wrap","wearing a rune enchanter's glyphic vestments",
            "wearing a polar explorer's icy ensemble","wearing a mystic falconer's feathered garb",
            "wearing a cosmic druid's nebulous cloak","wearing an oracle's vision-inspired dress",
            "wearing a dream walker's somnolent outfit","wearing a molten forger's lava-streaked apron",
            "wearing a twilight sentinel's dusk cloak","wearing a feral shapeshifter's mutable attire",
            "wearing a sky charioteer's cloud-kissed robes","wearing a tidal summoner's oceanic gown",
            "wearing a blood alchemist's crimson garb","wearing a wind whisperer's gale-touched tunic",
            "wearing a desert mystic's sunbaked robes","wearing a frost monarch's shimmering regalia",
            "wearing a star harvester's astral jumpsuit","wearing an infernal diplomat's embered suit",
            "wearing a lightning juggler's charged ensemble","wearing a velvet assassin's shadowy attire",
            "wearing a cosmic scribe's constellation cloak","wearing a golden gladiator's sunlit armor",
            "wearing a quantum navigator's reality-bending outfit"
        ]
    },
    action: ['fighting', 'running'],
    scene: ['in the city streets,', 'in a meadow,', 'in the moutains,', 'in a sunset,'],
    lighting: ['soft lighting', 'sunlit', 'cinematic lighting', 'ambient lighting', 'neon lighting', 'sun rays'],
    details: ['reflections,', 'metal,', 'action packed,'],
    composition: ['8K,', 'high detail,', 'realistic,'],
    artistStyle: ['in the style of Dr. Seuss']
}